" Color and syntax highlighting
" Default colorscheme
colorscheme ron
set background=dark

" Syntax highlighting, fonts, etc.
set gfn=Monospace\ 14
syntax on
filetype on
filetype plugin on
filetype indent on
set laststatus=2
set modeline
set nocompatible
set textwidth=79

" Indenting and () matching
set autoindent
set shiftwidth=2
set smartindent
set smarttab
set softtabstop=2
set tabstop=2
set expandtab
set showmatch

" Folding
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2

" Searching
set hlsearch

" Turn off recording
map q <Nop>
